// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecetteApp.Data;

#nullable disable

namespace RecetteApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512154553_InitIdentity")]
    partial class InitIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RecetteApp.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Petit-déjeuner"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Déjeuner"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Dîner"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Dessert"
                        });
                });

            modelBuilder.Entity("RecetteApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CaloriesParUnite")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesParUnite = 3.64f,
                            Nom = "Farine de blé",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesParUnite = 8.84f,
                            Nom = "Huile d'olive",
                            Unite = "ml"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesParUnite = 78f,
                            Nom = "Oeuf",
                            Unite = "pièce"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesParUnite = 3.87f,
                            Nom = "Sucre",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesParUnite = 0.61f,
                            Nom = "Lait entier",
                            Unite = "ml"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesParUnite = 7.17f,
                            Nom = "Beurre",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesParUnite = 1.65f,
                            Nom = "Poulet",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesParUnite = 0.18f,
                            Nom = "Tomate",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesParUnite = 3.71f,
                            Nom = "Pates",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesParUnite = 3.6f,
                            Nom = "Riz",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 11,
                            CaloriesParUnite = 0.4f,
                            Nom = "Oignon",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 12,
                            CaloriesParUnite = 4.5f,
                            Nom = "Ail",
                            Unite = "gousse"
                        },
                        new
                        {
                            Id = 13,
                            CaloriesParUnite = 0f,
                            Nom = "Sel",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 14,
                            CaloriesParUnite = 2.51f,
                            Nom = "Poivre",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 15,
                            CaloriesParUnite = 0.82f,
                            Nom = "Concentre tomate",
                            Unite = "g"
                        });
                });

            modelBuilder.Entity("RecetteApp.Models.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Etapes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeCuisineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("TypeCuisineId");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("RecetteApp.Models.RecetteIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantite")
                        .HasColumnType("REAL");

                    b.Property<int>("RecetteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecetteId");

                    b.ToTable("RecetteIngredients");
                });

            modelBuilder.Entity("RecetteApp.Models.TypeCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypesCuisine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Tunisienne"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Française"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Italienne"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Méditerranéenne"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Orientale"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Internationale"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecetteApp.Models.Recette", b =>
                {
                    b.HasOne("RecetteApp.Models.Categorie", "Categorie")
                        .WithMany("Recettes")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecetteApp.Models.TypeCuisine", "TypeCuisine")
                        .WithMany("Recettes")
                        .HasForeignKey("TypeCuisineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("TypeCuisine");
                });

            modelBuilder.Entity("RecetteApp.Models.RecetteIngredient", b =>
                {
                    b.HasOne("RecetteApp.Models.Ingredient", "Ingredient")
                        .WithMany("RecetteIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecetteApp.Models.Recette", "Recette")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("RecetteApp.Models.Categorie", b =>
                {
                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("RecetteApp.Models.Ingredient", b =>
                {
                    b.Navigation("RecetteIngredients");
                });

            modelBuilder.Entity("RecetteApp.Models.Recette", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RecetteApp.Models.TypeCuisine", b =>
                {
                    b.Navigation("Recettes");
                });
#pragma warning restore 612, 618
        }
    }
}
